export const OPEN_MODAL_ADD = "OPEN_MODAL_ADD";
export const CLOSE_MODAL_ADD = "CLOSE_MODAL_ADD";
export const OPEN_MODAL_EDIT = "OPEN_MODAL_EDIT";
export const CLOSE_MODAL_EDIT = "CLOSE_MODAL_EDIT";
export const OPEN_MODAL_CHANGE_PASSWORD = "OPEN_MODAL_CHANGE_PASSWORD";
export const CLOSE_MODAL_CHANGE_PASSWORD = "CLOSE_MODAL_CHANGE_PASSWORD";
export const GETTING_MODAL_PRODUCT = "GETTING_MODAL_PRODUCT";
