export const GET_PRODUCTS = "GET_PRODUCTS";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const LOADING_PRODUCT = "LOADING_PRODUCT";
export const ERROR_IN_PRODUCT = "ERROR_IN_PRODUCT";
